Add export of stage.submittedAt
empiricaly/meteor-empirica-core pull request #117
Opened 2020-04-24 18:14 UTC by JamesPHoughton

Also, remove an extraneous curly brace from the lobby screen.

Exporting `stage.submittedAt` should let us compare how long each individual spends in a stage that has a 'submit' button. If 9/10 people are done in 2 minutes, but there's always one guy who takes the full 5 minutes, we want to know so we can adjust the stage default time. 

Not sure if `npm-shrinkwrap.json` wants to be included in the PR?

2020-04-25 03:34 UTC, npaton requested changes
Updating so many dependencies at once is a bit scary tbh. Would you mind removing the shrinkwrap from this PR?

Otherwise looking good. Thanks!

2020-04-25 03:34 UTC, npaton commented on ui/components/Game.jsx
> +
Wow, there was a curly bracket in the UI we didn't notice!? Thanks!

2020-04-27 18:35 UTC, JamesPHoughton commented
@npaton No problem!

2020-04-27 23:33 UTC, npaton approved these changes

2020-04-27 23:34 UTC, merged