Fixes/bulk operations db 90
empiricaly/meteor-empirica-core pull request #95
Opened 2020-02-28 04:09 UTC by hubertusputu1

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-02-29 13:36 UTC, npaton requested changes
LGTM. Just check on that insertOption, I don't think it's necessary.
And just make sure you have the exact same docs inserted.
Can you notice a marked performance improvement. You might need to try on a high round/stage game to feel the effect on a local dev setup. Let me know what kind of improvement you're seeing. Thanks!

2020-02-29 13:36 UTC, npaton commented on api/games/create.js
> +      insertOption
I don't think these insertOption apply to Bulk ops, those options have to do with SimpleSchema, which is not part of Mongo.

2020-03-02 14:11 UTC, hubertusputu1 commented
@npaton , I did the test local dev setup. this is what i got:

test environment: 100 rounds, 100 stages, 1 player
before changes: it takes 26 - 30s
after changes: it takes 5 - 8s

i also checked that bulk insertions have exact same docs on the db.

2020-03-03 02:00 UTC, npaton commented
Great! Could I ask you to do one more test, for performance and verification of the records. Just to be sure, please run one test with multiple players: 100 rounds, 5 stages each, 10 players. I just want to make sure we have all player-rounds and player-stages created. And we'll post the performance improvements for both of these scenarios.
Otherwise, that's it, one more test, and it looks like we'll be ready to merge. Great stuff!

2020-03-03 04:29 UTC, hubertusputu1 commented
@npaton i did the test that you requested:

test environment: 100 rounds, 5 stages each, 5 players
before changes: it takes 8 - 10s
after changes: it takes less than 5s

rounds, stages, player_rounds, player_stages collections also has been checked that still insert the same docs.

2020-03-03 05:54 UTC, npaton approved these changes

2020-03-03 05:55 UTC, npaton commented
Great! Feel free to merge, and let the corresponding ticket know that the improvement will appear in the upcoming next version of Empirica.

2020-03-03 09:49 UTC, merged